#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use list_modules;
use modules;

# based on install::commands
sub modprobe {
    !@_ || $_[0] =~ /^-?-h/ and die "usage: modprobe <module> [<options...>]\n";
    # kernel calls us with modprobe -q -- <module>, so ignore options
    my $name = shift;
    while (substr($name, 0, 1) eq "-") {
	$name = shift;
    }
    list_modules::load_default_moddeps();
    modules::load_with_options([ $name ], { $name => join(' ', @_) });
}

$::isInstall = 1;
modprobe(@ARGV);
