#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use list_modules;
use modules;

# based on install::commands
sub modprobe {
    !@_ || $_[0] =~ /^-?-h/ and die "usage: modprobe <module> [<options...>]\n";
    my $name = shift;
    list_modules::load_default_moddeps();
    modules::load_with_options([ $name ], { $name => join(' ', @_) });
}

$::isInstall = 1;
modprobe(@ARGV);
