#!/usr/bin/perl

# Copyright (c) 2004 Mandrakesoft
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib qw(/usr/lib/libDrakX);

use common;
use standalone;
use Digest::MD5 qw(md5_hex);
use network::network;

# md5_hex call came from move::machine_ident() :
my $id = "MDK" . md5_hex(join("", (map { (split)[1] } cat_("/proc/bus/pci/devices"))));

my $net = {};

# first boot wizard:
!glob_("/etc/netprofile/profiles/MDK*") and system('/usr/sbin/mdkmove');

# create hardware profile if needed:
if (! -d "/etc/netprofile/profiles/$id") {
    network::network::netprofile_read($net);
    network::network::netprofile_add($net, $id);
}

# restore hardware profile:
eval { network::network::netprofile_set($net, $id) };

# redo ldconfig cache for libGL (since we've both ATI and NVIDIA GLX packages):
system("/sbin/ldconfig");
