CFLAGS=  -I../include/net $(RPM_OPT_FLAGS)
OBJS = pppdump.o bsd-comp.o deflate.o zlib.o

INSTALL= install

all:	pppdump

pppdump: $(OBJS)
	$(CC) $(RPM_OPT_FLAGS) -o pppdump $(OBJS)

clean:
	rm -f pppdump $(OBJS) *~

install:
	mkdir -p $(BINDIR) $(MANDIR)/man8
	$(INSTALL) -s -c pppdump $(BINDIR)
	$(INSTALL) -c pppdump.8 $(MANDIR)/man8
