ROOTDEST = /export
MISC_DEST = $(ROOTDEST)/misc
GENERIC_INSTALL_DEST = $(ROOTDEST)/install
EXTRA_INSTALL_DEST = $(GENERIC_INSTALL_DEST)/extra
IMAGES_DEST = $(GENERIC_INSTALL_DEST)/images
STAGE2_DEST = $(GENERIC_INSTALL_DEST)/stage2
STAGE2_LIVE = $(STAGE2_DEST)/live

MAIN_RPMS_DIR = $(ROOTDEST)/media/main
MEDIA_INFO_DEST = $(ROOTDEST)/media/media_info

DISTRIB_NAME = Mandrakiva
DISTRIB_VERSION = 2006
DISTRIB_DESCR = "$(DISTRIB_NAME) release $(DISTRIB_VERSION)"


# not config, but useful everywhere :)
ARCH := $(patsubst i%86,i386,$(shell uname -m))
ARCH := $(patsubst sparc%,sparc,$(ARCH))

ifeq (x86_64, $(ARCH))
LIB = lib64
else
LIB = lib
endif
