_DISTRIB_NAME := $(shell sed -n '/^.*distribution=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_NAME = $(shell sed -n '/^.*distribution=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_VERSION = $(shell sed -n '/^.*version=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_TYPE = $(shell sed -n '/^.*type=\([^,]*\),.*/s//\1/p' /etc/product.id)
#DISTRIB_DESCR = "$(_DISTRIB_NAME) release $(DISTRIB_VERSION)"
DISTRIB_FULLNAME = $(shell sed -e 's/.*$(DISTRIB_VERSION) //g' -e 's/ for .*//g' /etc/release)
#sed -e s/.*2013.0 //g /etc/release)
DISTRIB_DESCR = "$(DISTRIB_NAME) $(DISTRIB_VERSION) $(DISTRIB_FULLNAME)"

# not config, but useful everywhere :)
ARCH := $(patsubst i%86,i386,$(shell uname -m))
ARCH := $(patsubst sparc%,sparc,$(ARCH))
ARCH := $(patsubst arm%,arm,$(ARCH))

PKG_ARCH := $(patsubst i386,i586,$(ARCH))

ifeq (x86_64, $(ARCH))
LIB = lib64
else
LIB = lib
endif

FAMILY = drakx-installer
PREFIX = /usr
LOCATION = $(PREFIX)/$(LIB)/$(FAMILY)
ROOTDEST = $(LOCATION)/root
STAGE2_DEST = $(ROOTDEST)/install/stage2
