#!/usr/bin/perl

use MDK::Common;
use lib qw(/usr/lib/libDrakX);
use xf86misc::main;

my $nb = 0;
$| = 1;
print "waiting for X";
foreach (1..30) {
    print ".";
    sleep 1;
    print("no X server :(\n"), exit 1 if !fuzzy_pidofs(qr/\bX_move\b/);
    $nb++ if xf86misc::main::Xtest(':0');
    if ($nb > 2) { #- one succeeded test is not enough :-(
        print "found\n";
        exit 0;
    }
}
print "not found\n";
exit 1;
