.TH DRAKCONNECT 8 "17 November 2003" "drakxtools" "Linux Administrator's Manual"
.SH NAME
drakconnect \- configure network interfaces
.SH SYNOPSIS
.B "drakconnect"
.br
.B "drakconnect --skip-wizard"
.SH DESCRIPTION
.B Drakconnect
is used to configure the network interfaces.

Drakconnect handle ISDN, modems, xDSL, LAN as well as wirelles
connexions.

There's two main modes: the wizard mode and the "embedded in mcc" view
(the manage interface=.  In the wizard mode, drakconnect detect all
network interfaces and offer to configure them.

.SH OPTIONS
.TP
.B "\-\-del"
Delete a network interface and all related files
.B "\-\-expert"
Expert mode; give access to more options (advanced options are show by
default and some extra steps occured in the wizard)
.TP
.B "\-\-help"
Display short description of drakconnect options
.TP
.B "\-\-skip-wizard"
Enable or disable the use of the ARP protocol on this interface.
.TP
.B "\-\-testing"
Do not do anything (for debugging purpose)
.SH FILES
.SS Name resolution
.I /etc/sysconfig/network
global network options (hostname, is networking enabled, default gateway)
.br
.I /etc/hosts
hosts to IPs mapping
.br
.I /etc/resolv.conf
domain, primary & secondary DNS
.br
.SS Kernel interfaces list
.I /proc/net/dev
network interfaces and their stats
.br
.I /proc/net/if_inet6
the same for ipv6
.br
.I /sys/class/net/*/
per network interface sysfs interface
.br
.SS Interfaces configuration
.I /etc/modules.conf and /etc/modprobe.conf
logical network interfaces (eg: ethX) to kernel driver mapping
.br
.I /etc/iftab
enable to remap interfaces names depending on ARP or MAC addresses,
kernel driver, ... (see
.BR iftab (5)
for further information)
.br
.I /etc/sysconfig/network-scripts/ifcfg-*
per interface configuration (ip/network, ip discovery
protocol, link notification support, ...) (see
.BR ifcfg (8)
for further information)
.br
.I /etc/profile.d/proxy.csh /etc/profile.d/proxy.sh 
proxy configuration
.SS Profiles
.I /etc/netprofile/
the directory where profiles are saved
.br
.I /etc/netprofile/current
this file hold the current profile name
.br
.I /etc/netprofile/list
this file list the files to save in profiles
.br
.SS Peer
.I /etc/ppp/options
generic pppd options
.br
.I /etc/ppp/peers/ppp0
pppd options for provider (ISP)
.br
.I /etc/ppp/pap-secrets and /etc/ppp/chap-secrets
peer authentication data (login and passwords)
.br
.I /etc/ppp/pppoe.conf
ppoe configuration file. see pppoe.conf(8)
.SH BUGS
.SH SEE ALSO
arp(8), ethtool(8), ifcfg(5), ifconfig(8), ipchains(8), pppd(8), netstat(8), rarp(8), route(8),
.SH AUTHORS
Damien "Dam's" Krotkine,
.br
Damien Chaumette,
.br
Francois Pons,
.br
Thierry Vignaud <tvignaud@mandrakesoft.com>
.br
Olivier blin <blino@mandrakesoft.com>
