/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define AUTOCONF_INCLUDED
#define __IN_PCMCIA_PACKAGE__

#define LINUX "/home/gc/rpm/BUILD/linux"
#define PREFIX "/home/gc/rpm/tmp/kernel-2.4.0-build"
#define CC "/usr/bin/kgcc"
#define LD "ld"
#define KFLAGS ""
#define UFLAGS ""
#define PCDEBUG ""
#define USE_PM 1
#define UNSAFE_TOOLS 1
#define CONFIG_CARDBUS 1
#undef  CONFIG_PNP_BIOS
#define MODDIR "/lib/modules/2.4.0-6mdk"

/* Options from /home/gc/rpm/BUILD/linux/.config */
#define CONFIG_MODULES 1
#undef  CONFIG_PCMCIA
#undef  CONFIG_SMP
#define CONFIG_PCI 1
#define CONFIG_PCI_QUIRKS 1
#define CONFIG_PM 1
#define CONFIG_SCSI 1
#define CONFIG_IEEE1394 1
#define CONFIG_INET 1
#define CONFIG_NET_PCMCIA_RADIO 1
#define CONFIG_TR 1
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_DIVERT
#define CONFIG_MODVERSIONS 1
#define CONFIG_X86_L1_CACHE_BYTES 32
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_PROC_FS 1
#define ARCH "i386"
#define HOST_ARCH "i386"
#define AFLAGS ""
#define CONFIG_ISA 1
#define CONFIG_UID16 1

#define UTS_RELEASE "2.4.0-6mdk"
#define UTS_VERSION "#1 Wed Jan 24 16:10:16 CET 2001"
#define LINUX_VERSION_CODE 132096
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#define HAS_PROC_BUS 1
#define SYSV_INIT 1
#define RC_DIR "/etc/rc.d"
#undef  HAS_FORMS
#define MANDIR "/usr/share/man"
#define XMANDIR "/usr/X11R6/man"

#endif /* _PCMCIA_CONFIG_H */
