#!/usr/bin/perl
#- PERL_INSTALL_DEBUG is used to launch stage2 in debug mode

#- Mandrake Graphic Install $Id$
#- Copyright (C) 1999/2000 MandrakeSoft (pixel@mandrakesoft.com)
#-
#- This program is free software; you can redistribute it and/or modify
#- it under the terms of the GNU General Public License as published by
#- the Free Software Foundation; either version 2, or (at your option)
#- any later version.
#-
#- This program is distributed in the hope that it will be useful,
#- but WITHOUT ANY WARRANTY; without even the implied warranty of
#- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#- GNU General Public License for more details.
#-
#- You should have received a copy of the GNU General Public License
#- along with this program; if not, write to the Free Software
#- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use diagnostics;
use strict;

BEGIN {
    #- for testing purpose
    (my $f = __FILE__) =~ s|install2$|list_modules.pm|;
    -e $f or symlink '../kernel/list_modules.pm', $f;
}

use lib qw(/usr/bin/perl-install .);
use install2;

$::testing = $ENV{PERL_INSTALL_TEST};
$::isStandalone = 0;

install2::main(@ARGV);

c::_exit(0);
