#!/bin/sh

dir=`pwd`/../../..

/bin/rm -rf /tmp/rhimage
mkdir -m 0700 /tmp/rhimage || exit 1
/bin/rm -rf /tmp/drakx
mkdir -m 0700 /tmp/drakx || exit 2

for i in Mandrake RPMS misc boot images
do
    ln -sf "$dir/../../$i" "/tmp/rhimage/$i" 
done

/bin/cp -a "$dir/../../Mandrake/mdkinst" "/tmp/drakx"

if [ -x "/tmp/drakx/mdkinst/usr/bin/perl-install/live_install2" ]; then
    $perlcoredir=/usr/lib/perl5/5.6.0/i386-linux/CORE
    cd /tmp/drakx/mdkinst/usr/bin/perl-install
    if [ -x $perlcoredir/libperl.so ]; then
	mv $perlcoredir/libperl.so /tmp/drakx/mdkinst
    else
	mkdir -p $perlcoredir
	ln -sf /tmp/drakx/mdkinst/$perlcoredir/libperl.so $perlcoredir/libperl.so
    fi

    ../../../lib/ld-linux.so.2 ../perl ./live_install2

    rm -f $perlcoredir/libperl.so
    if [ -x /tmp/drakx/mdkinst ]; then
	mv /tmp/drakx/mdkinst/libperl.so $perlcoredir/libperl.so
    fi
else
    echo >&2 "unable to get a working live system to start, check your working directory"
fi

#/bin/rm -rf /tmp/drakx
#/bin/rm -rf /tmp/rhimage
