# -*- Makefile -*-
VERSION:=17.44

SUDO        = sudo
TMPDIR      = /tmp
SO_FILES    = c/blib/arch/auto/c/c.so                                                                 

# PMS_DIRS is used only in drakxtools
PMS_DIRS    = c diskdrake harddrake interactive modules partition_table resize_fat security fs fs/remote

PMS         = *.pm $(PMS_DIRS:%=%/*.pm) install/*.pm install/help/*.pm install/commands install/install2
STANDALONEPMS_ = adduserdrake bootloader-config display_help display_release_notes.pl diskdrake drakauth drakautologin drakboot drakbug drakbug_report drakclock drakedm drakdvb drakfont drakhelp drakperm draksec draksound drakupdate_fstab drakups drakxservices drakxtv fileshareset finish-install harddrake2 localedrake logdrake lsnetdrake notify-x11-free-driver-switch remove-unused-packages scannerdrake service_harddrake service_harddrake_confirm

STANDALONEPMS = $(STANDALONEPMS_:%=standalone/%)
ALLPMS	    = $(PMS) $(STANDALONEPMS)
PERL        = perl
LOCALFILES  = $(patsubst %, ../tools/%,serial_probe/serial_probe)
DIRS        = c resize_fat #po 
CFLAGS	    = -Wall
override CFLAGS  += -pipe

