# -*- Makefile -*-
ARCH := $(patsubst i%86,i386,$(shell uname -m))
ARCH := $(patsubst sparc%,sparc,$(ARCH))

ifeq (x86_64, $(ARCH))
LIB = lib64
else
LIB	= lib
endif

VERSION     = 2.2.10-BOOT                                                                             
SUDO        = sudo
SO_FILES    = c/blib/arch/auto/c/c.so                                                                 
PMS_DIRS    = Newt Xconfig c xf86misc diskdrake harddrake interactive modules network partition_table printer resize_fat sbus_probing security 
PMS         = *.pm $(PMS_DIRS:%=%/*.pm) commands install2
STANDALONEPMS_ = XFdrake adduserdrake diskdrake drakTermServ drakautoinst drakauth drakbackup drakboot drakbug drakbug_report drakclock drakconnect drakedm drakfirewall drakfloppy drakfont drakgw drakhelp drakperm drakproxy drakpxe draksec draksound draksplash drakupdate_fstab drakups drakvpn drakxservices drakxtv fileshareset harddrake2 keyboarddrake localedrake logdrake lsnetdrake mousedrake net_applet net_monitor printerdrake scannerdrake service_harddrake service_harddrake_confirm

STANDALONEPMS = $(STANDALONEPMS_:%=standalone/%)
ALLPMS	    = $(PMS) $(STANDALONEPMS) share/advertising/*.pl
REP4PMS     = /usr/bin/perl-install
ROOTDEST    = /export
DEST        = $(ROOTDEST)/Mandrake/mdkinst
STAGE2      = $(ROOTDEST)/Mandrake/base/mdkinst_stage2
BASE        = $(ROOTDEST)/Mandrake/base
DESTREP4PMS = $(DEST)$(REP4PMS)
PERL        = perl
LOCALFILES  = $(patsubst %, ../tools/%,ddcprobe/ddcxinfos serial_probe/serial_probe xhost+)
DIRS        = c Newt resize_fat xf86misc #po 
CFLAGS	    = -Wall
override CFLAGS  += -pipe

