# -*- Makefile -*-
VERSION     = 2.2.10-BOOT                                                                             
SUDO        = sudo
TMPDIR      = /tmp
SO_FILES    = c/blib/arch/auto/c/c.so                                                                 
PMS_DIRS    = Newt Xconfig c xf86misc diskdrake harddrake interactive modules network partition_table printer resize_fat sbus_probing security fs
PMS         = *.pm $(PMS_DIRS:%=%/*.pm) commands install2
STANDALONEPMS_ = XFdrake adduserdrake autosetupprintqueues diskdrake drakTermServ drakautoinst drakauth drakbackup drakboot drakbug drakbug_report drakclock drakconnect drakedm drakfirewall drakfloppy drakfont drakgw drakhelp drakperm drakproxy drakroam draksec draksound draksplash drakupdate_fstab drakups drakvpn drakxservices drakxtv fileshareset harddrake2 finish-install keyboarddrake listsupportedprinters localedrake logdrake lsnetdrake mousedrake net_applet net_monitor printerdrake scannerdrake service_harddrake service_harddrake_confirm bootloader-config drakhosts draknfs

STANDALONEPMS = $(STANDALONEPMS_:%=standalone/%)
ALLPMS	    = $(PMS) $(STANDALONEPMS) share/advertising/*.pl share/compssUsers.pl*
REP4PMS     = /usr/lib/libDrakX
ROOTDEST    = /export
DEST        = $(STAGE2_LIVE)
DESTREP4PMS = $(DEST)$(REP4PMS)
PERL        = perl
LOCALFILES  = $(patsubst %, ../tools/%,serial_probe/serial_probe xhost+)
DIRS        = c Newt resize_fat xf86misc #po 
CFLAGS	    = -Wall
override CFLAGS  += -pipe

