#!/usr/bin/perl -n

/^#/ and next;
/c::to_utf8/ || /c::from_utf8/ and next;
/\bc::(\w+)/ and push @c, [ $1, $ARGV, $. ] ;

eof && close ARGV;

END {
    $_ = join '', `cat c/stuff.xs.pl`; 
    foreach $c (@c) {
	/$c->[0]/ or $err = print "$c->[1]:$c->[2]: $c->[0] not in c.xs\n";
    }
    exit $err;
}
