.\" 
.TH drakbackup 5 "December 2005" Mandriva "System Utilities"
.SH NAME 
drakbackup

.SH DESCRIPTION 
Drakbackup is a backup/restore application for Mandriva Linux. Most users will want to use the GUI interface, but it is also possible to run the application from the
command line.

.B "Command Line Options"

.B
 --default
    Run a backup using the default configuration.

.B
 --profile
    Run a backup using a different profile. (Profiles are alternate, named configurations located in the same directory as the default configuration; i.e. foo.conf).

.B
 --debug
    Run drakbackup in debugging mode, which will output additional information for troubleshooting.

.B 
 --show-config
    Display the configuration summary.

.B
 --cd-info
    Dump the capabilities table of attached CD/DVD hardware.

.B
 --daemon
    Intended to be used in cron scripts. Runs drakbackup in daemon mode, using defined media methods for unattended  backups.

.SH "SEE ALSO"
.BR drakbackup.conf (5),
.BR /usr/share/doc/mandriva/en/Drakxtools-Guide.html/drakbackup.html

.SH AUTHOR
Stew Benedict <sbenedict@mandriva.com>

