#!/bin/sh

[ "$1" = "-f" ] || { echo "Call it with option -f, but don't fear loosing all your data, this command is dangerous!"; exit 1; }

echo "I'm going to install the oem version on your hard drive"
echo "!!ALL DATA IS GOING TO BE LOST!!"
echo
echo "Press enter to go on"

read

cd /proc/ide
for i in hd*; do
  grep -q disk  $i/media && hd=/dev/$i
  grep -q cdrom $i/media && cd=/dev/$i
done

echo "hd: $hd"
echo "cdrom: $cd"

mkdir /cdrom ; mount -r -t iso9660 $cd /cdrom

echo "Installing new partition table and bootloader"
dd if=/etc/part_and_bootloader of=$hd
  
echo "Asking kernel to take into account this new partition table"
kernel_read_part $hd

echo "Formatting (ext2) partition"
mkfs.ext2 ${hd}1

echo "Mounting partition"
mkdir /hd ; mount -t ext2 ${hd}1 /hd

echo "Copying cdrom on hard drive"
cp -a /boot /cdrom/boot /cdrom/Mandrake /hd
rm /hd/Mandrake/mdkinst/usr/bin/runinstall2

echo "Done, oem hard drive ready! Press enter to reboot"
read
reboot