#!/bin/sh

[ "$1" = "-f" ] || { echo "Call it with option -f, but don't fear loosing all your data, this command is dangerous!"; exit 1; }

inst=1
swap=2
root=3
langs=fr:en

echo
echo
echo "I'm going to install the OEM version on your hard drive"
echo "[1;31;40m!!ALL DATA IS GOING TO BE LOST!![0m"
echo
echo "Press enter to go on"

read

cd /proc/ide
for i in hd*; do
  grep -q disk  $i/media && hd=/dev/$i
  grep -q cdrom $i/media && cd=/dev/$i
done

echo "hd: $hd"
echo "cdrom: $cd"

mkdir /cdrom ; mount -r -t iso9660 $cd /cdrom

echo "Installing new partition table and bootloader"
dd if=/etc/part_and_bootloader of=$hd
  
echo "Asking kernel to take into account this new partition table"
kernel_read_part $hd

echo "Setting swap"
mkswap $hd$swap
swapon $hd$swap

echo "Formatting $hd$inst partition" ; mkfs.ext2 $hd$inst
echo "Formatting $hd$root partition" ; mkfs.ext2 $hd$root

echo "Mounting partitions"
mkdir -p /hd ; mount -t ext2 $hd$inst /hd
mkdir -p /mnt; mount -t ext2 $hd$root /mnt

echo "Copying installation on hard drive"
cp -a /boot /cdrom/boot /cdrom/Mandrake /hd

echo "Installing packages"
export DURING_INSTALL=1
export RPM_INSTALL_LANG=$langs
export LD_LIBRARY_PATH=/usr/X11R6/lib
export SECURE_LEVEL=2
for i in /etc /var/lib/rpm /proc ; do mkdir -p /mnt$i; done
mount -t proc proc /mnt/proc
rpm --root /mnt --initdb
touch /mnt/etc/fstab
for i in `perl -pe 's/ .*//' /cdrom/Mandrake/base/depslist.ordered`; do
    [ -e /cdrom/RPMS/$i.*.rpm ] && rpm --root /mnt -ivh /cdrom/RPMS/$i.*.rpm --nodeps --force
done
umount /mnt/proc

echo
echo "Done. OEM hard drive ready!"
echo "Press enter to reboot"
read
reboot
