#!/bin/sh

. /etc/init.d/functions

# test for an up interface != lo
if test "x"`ifconfig | cut -d ' ' -f 1 | grep -v '^$' | grep -v lo` = "x"; then
	echo "There is no up interface, you can try to execute 'drvinst' to find drivers and 'dhcp-client' to configure your interface for DHCP." >&2
	exit 5
fi

# set a password
echo "Set root password for login:"
passwd root

echo ""
action "Starting ssh daemon... " dropbear -E 2>/var/log/dropbear.log
