include ../../Makefile.config

install:
	rm -rf $(ROOTDEST)/Mandrake/share/advertising
	install -d $(ROOTDEST)/Mandrake/share/advertising
	install -m755 *.pl $(ROOTDEST)/Mandrake/share/advertising
	install -m644 *.png $(ROOTDEST)/Mandrake/share/advertising
	install -m644 list $(ROOTDEST)/Mandrake/share/advertising
