#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use standalone;     #- warning, standalone must be loaded very first, for 'explanations'

use common;
use interactive;
use any;

my $isMD5 = cat_("/etc/pam.d/system-auth") =~ /md5/;
my $isShadow = cat_("/etc/pam.d/system-auth") =~ /shadow/;


my $users = []; 
my $in;

if (my @l = grep { ! /^-/ } @ARGV) {
    $users = [ map { { name => $_, realname => $_ } } @l ];
} else {
    $in = 'interactive'->vnew('su');
    any::ask_users($in, $users, $ENV{SECURE_LEVEL}, []);
}

system("adduser", $_->{name}) foreach @$users;
any::write_passwd_user($_, $isMD5) foreach @$users;
system("pwconv") if $isShadow;

any::addUsers($users);

$in->exit(0) if $in;
