#!/usr/bin/perl

use strict;
use diagnostics;

use lib qw(/usr/lib/libDrakX);
use standalone;     #- warning, standalone must be loaded very first, for 'explanations'

use interactive;
use common;
use any;
use ctxhelp;
use log;


sub usage() {
    print STDERR N(" drakhelp 0.1
Copyright (C) 2003-2005 Mandriva.
This is free software and may be redistributed under the terms of the GNU GPL.

Usage: 
") . N(" --help                - display this help     
") . N(" --id <id_label>       - load the html help page which refers to id_label
") . N(" --doc <link>          - link to another web page ( for WM welcome frontend)
");
    exit(0);
}
my ($opt, $idlabel) = @ARGV;
@ARGV == 2 && ($opt eq '--id' || $opt eq '--doc' || $opt eq '--help') or usage();

$ugtk2::wm_icon = "help";
my $in = interactive->vnew;
my ($instpath, $ancpath, $package) = ctxhelp::path2help($opt, $idlabel);

-e $instpath or system("/usr/sbin/drakhelp_inst $package");
-e $instpath or $in->ask_warn(N("Mandriva Linux Help Center"), N("%s cannot be displayed \n. No Help entry of this type\n", $instpath));

system("/usr/bin/www-browser file://$ancpath &") if -e $instpath;
