#!/usr/bin/perl

use strict;
use lib qw(/usr/lib/libDrakX);

use standalone;     #- warning, standalone must be loaded very first, for 'explanations'

use common;
use interactive;
use services;
use log;

my $in = 'interactive'->vnew('su', 'services');
begin:
my $l = services::ask($in);
services::doit($in, $l) if $l;
!$::isEmbedded and $in->exit(0);
kill 'USR1', $::CCPID;
goto begin;
