#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use common;
use any;

my %other = (
    'rpm -qa' => join('', sort `rpm -qa`),
    'mandrake version' => mandrake_release(),
    'df' => join('', `df`),
);

print any::report_bug('', %other);
