#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use standalone;     #- warning, standalone must be loaded very first, for 'explanations'

use interactive;
use keyboard;
use Xconfigurator_consts;
use common;
use c;

local $_ = join '', @ARGV;

/-h/ and die "usage: drakxconf\n";
/-version/ and die "version: $Id$\n";

my $in = 'interactive'->vnew('su', 'default');
my @l=(
       { des => 'Display Configuration',
	 cmd => 'XFdrake'},
       { des => 'KeyBoard Configuration',
	 cmd => 'keyboarddrake'},
       { des => 'Mouse Configuration',
	 cmd => 'mousedrake'},
       { des => 'Hardware Information',
	 cmd => 'harddrake'},
       { des => 'Internet & Network',
	 cmd => 'drakconnect'},
       { des => 'Printer Configuration',
	 cmd => 'printerdrake'},
       { des => 'Add new users',
	 cmd => 'adduserdrake'},
       { des => 'Service Configuration',
	 cmd => 'drakxservices'},
       { des => 'Security Levels',
	 cmd => 'draksec'},
       { des => 'Boot Configuration',
	 cmd => 'drakboot'},
       { des => 'Auto Install',
	 cmd => 'drakautoinst'},
       { des => 'Connection Sharing',
	 cmd => 'drakgw'},
       { des => 'Diskdrake',
	 cmd => 'diskdrake'},
      );
my $choice = $in->ask_from_listf(_("Control Center"),
			    _("Choose the tool you want to use"),
			    sub { (int grep { -x "$_/" . $_[0]{cmd} } split (":", $ENV{PATH})) ? $_[0]{des} : ()  },#grep { my $prog = $_; int grep { -x "$_/$prog" } split ":", $ENV{PATH} } $_[0]{des} },
			    \@l ) or $in->exit(1);
$in->end;

exec $choice->{cmd}, @ARGV or $in->exit(1);
