#!/usr/bin/perl
# DrakxSound
# Copyright (C) 2002 MandrakeSoft (tvignaud@mandrakesoft.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib qw(/usr/lib/libDrakX);

use standalone;     #- warning, standalone must be loaded very first, for 'explanations'
 
use strict;
use interactive;
use detect_devices;
use common;
use harddrake::sound;

("@ARGV" =~ /--help|-h/) and die "usage: draksound [-h] [--help]\n";


my $in = 'interactive'->vnew();

use modules;

#no strict 'subs';
modules::mergein_conf('/etc/modules.conf');

my @devices = grep { $_->{media_type} eq 'MULTIMEDIA_AUDIO' } detect_devices::probeall(1);
if (@devices) {
    # TODO: That need some work for multiples sound cards
    foreach (@devices) {
	   # we should overwrite $device->{driver} with the right sound-slot-XX
	   $_->{driver} = modules::get_alias('sound-slot-0');
	   harddrake::sound::config($in, $_);
    }
} else {
    $in->ask_warn(_("No Sound Card detected!"), formatAlaTeX(
											   _("No Sound Card has been detected on your machine. Please verify that a Linux-supported Sound Card is correctly plugged in.


You can visit our hardware database at:


http://www.linux-mandrake.com/en/hardware.php3")));
}

modules::write_conf;
$in->exit(0);
