#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use common qw(:common :functional :file);
use interactive;
use standalone;
use services;
use log;

local $_ = join '', @ARGV;

/-h/ and die "usage: drakxservices\n";


my $in = vnew interactive('su');
my $l = services::ask($in);
services::doit($in, $l) if $l;

$in->exit(0);
