#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);

use common qw(:system :file);
use interactive;
use mouse;
use c;

local $_ = join '', @ARGV;

/-h/ and die "usage: draksec [--expert]\n";

$::expert = /-expert/ || cat_("/etc/sysconfig/system") =~ /^CLASS="?expert/m; #"
$::isStandalone = 1;

my $in = vnew interactive('su');

my %m = reverse (my %l = (
  0 => _("Welcome To Crackers"),
  1 => _("Poor"),
  2 => _("Low"),
  3 => _("Medium"),
  4 => _("High"),
  5 => _("Paranoid"),
));
my %help = (
  0 => _("This level is to be used with care. It makes your system more easy to use,
but very sensitive: it must not be used for a machine connected to others
or to the Internet. There is no password access."),
  1 => _("Password are now enabled, but use as a networked computer is still not recommended."),
  2 => _("Few improvements for this security level, the main one is that there are
more security warnings and checks."),
  3 => _("This is the standard security recommended for a computer that will be used
to connect to the Internet as a client. There are now security checks. "),
  4 => _("With this security level, the use of this system as a server becomes possible.
The security is now high enough to use the system as a server which accept
connections from many clients. "),
  5 => _("We take level 4 features, but now the system is entirely closed.
Security features are at their maximum."),
);

delete @l{0,1,5} unless $::expert;
delete @help{0,1,5} unless $::expert;

if (my $level = $in->ask_from_list('', _("Choose security level") . "\n\n" . 
				   join('', map { "$l{$_}: $help{$_}\n\n" } keys %l), 
				   [ values %l ], $l{$ENV{SECURE_LEVEL}})) {
    my $w = $in->wait_message('', _("Setting security level"));
    $in->suspend;

    $ENV{LILO_PASSWORD} = ''; # make it non interactive
    system "/usr/sbin/msec", $m{$level};

    $in->resume;
}

$in->exit(0);
