#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use standalone;
use common;
use harddrake::ui;

if ("@ARGV" =~ /--help|-h/) {
    print "Harddrake 2\n", $harddrake::ui::license, N("\nUsage: harddrake [-h|--help] [--test]\n");
    exit;
}
$::isStandalone=1;

harddrake::ui->new;
