#!/usr/bin/perl

# printerdrake
# Copyright (C) 1999 MandrakeSoft (fpons@linux-mandrake.com)
# Original version for printer configuration from pad.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib qw(/usr/lib/libDrakX);

use interactive;
use printer;
use printerdrake;
use c;

local $_ = join '', @ARGV;

/-h/ and die "usage: printerdrake [--beginner] [--expert] [--auto] [--noauto] [--skiptest] [--testing]\n";

$::beginner = /-beginner/;
$::expert = /-expert/;
$::auto = /-auto/;
$::noauto = /-noauto/;
$::skiptest = /-skiptest/;
$::testing = /-testing/;
$::isStandalone = 1;

my $printer; eval { $printer = printer::getinfo('') };
/-lpr/ and $printer->{mode} = 'lpr';
/-cups/ and $printer->{mode} = 'cups';
$printer->{mode} ||= 'cups'; #- assume this default if nothing found.

my $in = vnew interactive('su');

printerdrake::main($printer, $in, sub { $in->suspend; system("urpmi --auto --best-output " . join(' ', @_)); $in->resume; });

$in->exit(0);
