#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use pkgs;
use interactive;
use do_pkgs;
use standalone;

my $in = interactive->vnew('su');
my $do_pkgs = do_pkgs::do_pkgs($in);
pkgs::remove_unused_packages($in, $do_pkgs);
