#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use common;
use lang;
use interactive;
use do_pkgs;
use run_program;
use standalone;

my $in = interactive->vnew;
my $wait = $in->wait_message(N("Localization packages removal"),
			     N("Finding unused localization packages..."));
my $do_pkgs = do_pkgs->do_pkgs($in);
my @unselected_locales = pkgs::detect_unselected_locale_packages($do_pkgs);
undef $wait;

#- we should have some gurpme
if (@unselected_locales &&
    $in->ask_yesorno(
	N("Localization packages removal"),
	N("The following localization packages do not seem to be useful for your system:") . "\n" .
	join("\n", map { "  " . $_ } sort(@unselected_locales)) . "\n" .
	N("Do you want to remove these packages?"))) {
    my $_wait = $in->wait_message(N("Please wait"), N("Removing packages..."));
    run_program::run('urpme', '--auto', @unselected_locales);
}

# use script from One to list language files (/usr/share/locale mainly) and remove them?
