#!/usr/bin/perl

# scannerdrake $Id$
# Yves Duret <yduret at mandrakesoft.com>
# Copyright (C) 2001 MandrakeSoft
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use lib qw(/usr/lib/libDrakX);
use interactive;
use common;
use standalone;
use scanner;

$::isEmbedded = ($::XID, $::CCPID) = "@ARGV" =~ /--embedded (\w+) (\w+)/;
for (@ARGV) {
    /^--version$/ and die 'version: $Id$ '."\n";
    /^--help$/ and die 'logdrake [--version] [--help] [--manual] [--device=dev] [--update-sane=sane_desc_dir] [--update-usbtable] [--dynamic=dev]';
    /^--update-usbtable$/ and do {scanner::updateScannerDBfromUsbtable(); exit;};
    /^--update-sane=(.*)$/ and do {scanner::updateScannerDBfromSane($1); exit;};
    /^--manual$/ and $::Manual=1;
    /^--dynamic=(.*)$/ and do { dynamic($1); exit;};
}

$in = 'interactive'->vnew('su', 'default');
$in->do_pkgs->install('sane-backends', 'xsane', if_($in->do_pkgs->is_installed('gimp'),'xsane-gimp'));
if ($::Manual) {manual(); quit();}
my $wait = $in->wait_message(_("Test ports"), _("Detecting devices ..."));
@f = scanner::findScannerUsbport();
$wait=undef;
(@f) ? auto() : manual();
quit();

sub auto {
    foreach (@f) { 
	if (member($_->{val}{DESCRIPTION}), keys %$scanner::scannerDB) {
	    my $name = $_->{val}{DESCRIPTION};
	    $name =~ s/\s$//; #some HP entry have a trailing space, i will correct usbtable asap
	    $in->ask_yesorno('scannerdrake',_("%s found on %s, configuring it ?",$name,$_->{port}),1) or manual();
	    tryConfScanner($name, $_->{port});
	}
    }
}

sub manual {
    my $s = $in->ask_from_treelist('scannerdrake', _("Select a scanner"), '|', [keys %$scanner::scannerDB]) or return;
    # DRIVER usb or scsi
    #print "$s\n";
    tryConfScanner($s);
}

sub dynamic {
    @f = scanner::findScannerUsbport();
    foreach (@f) { 
	if (member($_->{val}{DESCRIPTION}), keys %$scanner::scannerDB) {
	    my $name = $_->{val}{DESCRIPTION};
	    $name =~ s/\s$//; #some HP entry have a trailing space, i will correct usbtable asap
	    scanner::confScanner($name, $_->{port}) unless($scanner::scannerDB->{$model}{flags}{unsupported});
	}
    }
}

sub tryConfScanner {
    # take care if interactive ouptut is needed (unsupported, parallel..)
    my ($model, $port) = @_;
    if ($scanner::scannerDB->{$model}{flags}{unsupported}) {
	$in->ask_warn('scannerdrake', _("This %s scanner is unsupported", $model));
	return;
    }
    if ($scanner::scannerDB->{$model}{driver} =~ /Parport/) {
	$in->ask_warn('scannerdrake', _("This %s scanner uses parallel port, which is unsupported for the moment", $model));
	return;
    }
    scanner::confScanner($model,$port);
}

sub quit {
    $::isEmbedded ? kill(USR1, $::CCPID) : $in->exit(0);
}

#-----------------------------------------------
# $Log$
# Revision 1.4  2001/11/19 17:39:03  pablo
# Corrected English errors
#
# Revision 1.3  2001/11/19 10:50:37  yduret
# added dynamic support
#
# Revision 1.2  2001/11/12 15:19:54  yduret
# update
#
