#!/usr/bin/perl

use lib "/usr/lib/libDrakX";
use keyboard;

my $dir = "bkeymaps/usr/share/keymaps";
system("rm -rf bkeymaps ; mkdir -p bkeymaps/usr/share/keymaps");

foreach (keyboard::_keyboards()) {
    my $kmap = keyboard::keyboard2kmap($_);
    if (system("loadkeys -u -b $kmap > $dir/$kmap.bkmap") != 0) {
	warn "unknown kmap $kmap\n";
	unlink "$dir/$kmap.bkmap";
    }
}

system("tar cfJ bkeymaps.tar.xz -C bkeymaps usr") == 0 or die;
system("rm -rf bkeymaps");
