#!/usr/bin/perl

use rpmtools;

sub chop_version($) {
    ($_[0] =~ /(.*)-[^-]+-[^-]+/)[0] || $_[0];
}

sub read_compsslist {
    my ($file) = @_;
    my %compsslist;

    local *F;
    open F, $file or die "closurepkgs: unable to open compsslist file $file\n";
    foreach (<F>) {
	my ($name, $level) = /^\s*(\S+)\s+(\d+)/;
	$compsslist{$name} = $level;
    }
    close F;

    \%compsslist;
}

sub main {
    my ($dir, $lang) = @_;

    #- compute depslist on line directly.
    my $params = new rpmtools;
    foreach (glob("$dir/*.cz*")) { $params->read_hdlists($_) }
    $params->keep_only_cleaned_provides_files();
    foreach (glob("$dir/*.cz*")) { $params->read_hdlists($_) }
    $params->compute_depslist();

    my $compsslist = read_compsslist("$dir/compssList");

    #- DO NOT FORGET TO UPDATE HERE ACCORDING TO gi/perl-install/install_any.pm
    my @pkgs = qw(XFree86 XFree86-glide-module Device3Dfx Glide_V3-DRI Glide_V5 Mesa
		  dhcpcd pump dhcpxd dhcp-client isdn4net isdn4k-utils dev pptp-adsl-fr rp-pppoe ppp ypbind
		  rhs-printfilters lpr cups cups-drivers samba ncpfs ghostscript-utils
		  kernel-pcmcia-cs apmd cdrecord
		  );
    push @pkgs, "XFree86-$_" foreach qw(3DLabs 3dfx 8514 AGX FBDev I128 Mach8 Mach32 Mach64 Mono P9000 Rage128 S3 S3V SVGA VGA16 W32);

    #- closure the list of package to be kept for oem.
    my %closure;
    foreach (@pkgs) {
	$closure{$_} = 1;
	map { $closure{chop_version($_->{name})} = 1 } map { $params->{depslist}[$_] } map { split /\|/ } split ' ', $params->{info}{$_}{deps};
    }
    #- only if dependancy is ok.
    $closure{$_} = 1 foreach qw(xpp kups kisdn);

    #- closure the list of package to always install for oem. (level >= 50)...
    my %install;
    my @force_install;
    if ($params->{info}{"locales-$lang"}) {
	foreach (keys %{$params->{info}}) {
	    push @force_install, $_ if grep { $_ == $params->{info}{"locales-$lang"}{id} } split ' ', $params->{info}{$_}{deps};
	}
    } else {
	foreach (keys %{$params->{info}}) {
	    push @force_install, $_ if grep { $params->{depslist}[$_]{name} =~ /locales-/ } split ' ', $params->{info}{$_}{deps};
	}
    }
    push @force_install, qw(cups cups-drivers drakprofile draksync irda-utils numlock raidtools reiserfs-utils
			    Mesa Mesa-demos alsa alsa-utils);
    foreach (qw(
		Aurora xawtv kwintv xscreensaver-gl Mesa-demos xmms-mesa bzflag csmash gltron spacecup chromium tuxracer
		), @force_install, grep { $compsslist->{$_} >= 50 } keys %{$params->{info}}) {
	$install{$_} = 1;
	map { $install{chop_version($_->{name})} = 1 } map { $params->{depslist}[$_] } map { split /\|/ } split ' ', $params->{info}{$_}{deps};
    }

    #- remove base packages, which have to be installed, according to basesystem.
    delete $closure{'basesystem'};
    $install{'basesystem'} = 1;
    map { delete $closure{chop_version($_->{name})};
	  $install{chop_version($_->{name})} = 1 } map { $params->{depslist}[$_] } map { split /\|/ } split ' ', $params->{info}{'basesystem'}{deps};

    #- special packages that are to be move to closure always ...
    foreach (qw(kernel-smp kernel-linus kernel-secure hackkernel-smp hackkernel-linus hackkernel-secure
		Aurora xawtv kwintv xscreensaver-gl xmms-mesa bzflag csmash gltron spacecup chromium tuxracer
		)) {
	$params->{info}{$_} or next;
	$closure{$_} = 1;
	delete $install{$_};
    }

    #- dump out the list of package according to the 2 lists defined above.
    my $total_install = 0;
    my $total_closure = 0;
    foreach (@{$params->{depslist}}) {
	my $tiny_name = chop_version($_->{name});
	if (exists $install{$tiny_name}) {
	    my $p = $params->{info}{$tiny_name};
	    $total_install += $p->{size};
	    print "I:$p->{name}-$p->{version}-$p->{release}\n";
	} elsif (exists $closure{$tiny_name}) {
	    my $p = $params->{info}{$tiny_name};
	    $total_closure += $p->{size};
	    print "C:$p->{name}-$p->{version}-$p->{release}\n";
	}
    }
    print "\n\ntotal_install=$total_install\n";
    print "total_closure=$total_closure\n";
}

main(@ARGV);
