#!/usr/bin/perl

use MDK::Common;

print join(' ', map {
		      my $arch = arch();
		      $arch = $compat_arch{$arch} while $arch && !-e "$_.$arch";
		      -e "$_.$arch" ? "$_.$arch" : $_;
		    } @ARGV), "\n";
